### ISSUE TITLE
During Installation the Armadillo & C+14 requirement causes a problem

### ISSUE THREAD

**Issue by utkuoguzman** [BioDynaMo/biodynamo#304]
**Describe the bug**
When I try to install BioDynaMo with the tutorial on the site, during the "curl https://biodynamo.org/install | bash" step at the end I get a C++14 Armadillo error:

"
Configuration completed. Creating Makefile... done.

[  2%] Performing build step for 'optim'
In file included from ./include/armadillo:23,
                 from ./include/misc/optim_options.hpp:76,
                 from ./include/optim.hpp:24,
                 from src/line_search/more_thuente.cpp:27:
./include/armadillo_bits/compiler_check.hpp:69:4: error: #error "*** C++14 compiler required; enable C++14 mode in your compiler, or use an earlier version of Armadillo"
   69 |   #error "*** C++14 compiler required; enable C++14 mode in your compiler, or use an earlier version of Armadillo"
"

**To Reproduce**
1. Do all the prerequisities on the site successfully.
2. write "curl https://biodynamo.org/install | bash" on the terminal 

**Screenshot**
![resim](https://user-images.githubusercontent.com/26433068/211213328-8c331be2-e764-4ab7-a209-04bd568fd1a2.png)

**Expected behavior**
I expected it to end successfully.

**Setup (please complete the following information):**
 - OS: Linux Ubuntu 20.04 in WSL2 (I know I know, no WSL is supported)
 - BioDynaMo version 1.04

**Additional context**
I just wanted to try the BioDynaMo in WSL2 and the installing method on the site doesn't let me enter an std flag to choose the c++14 version. I wondered if I can complete the installation and try the examples in WSL2. I also wonder how many changes required for a normal ubuntu and WSL2 version anyway.

THANKS

**Comment by TobiasDuswald** [comment]
Hi @utkuoguzman ,
sorry for the late reply, I just saw your problem now. Thank you also for the detailed description. The issue was that `armadillo` changed their default branch to a non-stable one and our `optim-lib` dependency clones the default branch. This caused the build failure. We fixed that issue right away in commit `b85681002e356a0d796691f0d9f9ed055a83af1f` but unfortunately, it occurred after the `1.04` release. 

If you were to install the latest master (or technically any commit after `b85681002e356a0d796691f0d9f9ed055a83af1f`) you should not have any trouble :)

via the one-line installer:

```
export BDM_INSTALL=master
curl https://biodynamo.org/install | bash
```

(I generally recommend working with the latest master to have access to the latest fixes and features. For the latest master, we're also testing daily so you can be sure that everything installs and works as expected)
