### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [BioDynaMo/biodynamo#329]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by TobiasDuswald** [comment]
Dear @igibek ,

I'm sorry for not getting back to you sooner. We activated the `Private vulnerability reporting` shortly after your request, but somehow we failed to communicate that to you. Thank you for taking a look at our software and checking if there are some vulnerabilities. We appreciate your effort!

If this resolves the issue, please feel free to close it, otherwise feel free to follow up with any question or comment and we'll try to be more responsive this time ;)

**Comment by vasvav** [comment]
Dear @igibek ,

I would also like to thank you attracting our attention regarding to the private vulnerability reporting feature on GitHub.
I think this has been dully taken care of, and we have enabled it in the BioDynaMo organisation while we have also automatically enabled this feature for all new public repos as well (following the how-to provided above). 

Hope this closes this issue; however, should we need to take any further action to amend things, please do not hesitate to give us a shout.

cheers
